production:
  google:
    key: UA-38250747-1
  mixpanel:
    key: '87c44c178fcff6bdebf572fc52692a46'
development:
  google:
    key: UA-38250747-1
  mixpanel:
    key: '87c44c178fcff6bdebf572fc52692a46'
